# Generated by Django 3.0.4 on 2020-03-25 01:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('first_Name', models.CharField(max_length=30)),
                ('last_Name', models.CharField(max_length=30)),
                ('email_Address', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=250)),
            ],
            managers=[
                ('Contact', django.db.models.manager.Manager()),
            ],
        ),
    ]
