# Generated by Django 3.0.4 on 2020-03-25 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20200325_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Contact.Contact')),
            ],
            bases=('Contact.contact',),
            managers=[
                ('Contact', django.db.models.manager.Manager()),
            ],
        ),
    ]
