# Generated by Django 3.0.7 on 2020-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_Address',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_Name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
